spring:
  profiles.active: local
---

spring:
  profiles: local
  datasource:
    springboot:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&charaterEncoding=utf-8
      username: springbooter
      password: springbooter123
      driverClassName: com.mysql.jdbc.Driver
    springweb:
      url: jdbc:mysql://localhost:3306/springweb?useUnicode=true&charaterEncoding=utf-8
      username: springweber
      password: springweber123
      driverClassName: com.mysql.jdbc.Driver

server:
    port: 8080


---
#
#spring:
#  profiles: integration
#server:
#    port: 8080
#datasource:
#    username: integration
#    password: integration
#    port: 3306
#
#logging:
#    file: server.log
#    level:
#        star: DEBUG
#        org.springframework: DEBUG
#        com.glass.memento: OFF
#
#---
#
#spring:
#  profiles: production
#server:
#    port: 8080
#datasource:
#    username: production
#    password: production
#    port: 3306
#logging:
#    file: server.log
#    level:
#        star: WARN
#        org.springframework: INFO
#        com.glass.memento: OFF

---